version: '3'

services:
  raycast:
    image: ghcr.io/yufeikang/raycast_api_proxy:main
    container_name: raycast
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CERT_FILE=/data/cert/backend.raycast.com.cert.pem
      - CERT_KEY=/data/cert/backend.raycast.com.key.pem
      - LOG_LEVEL=INFO
    ports:
      - "443:443"
    dns:
      - 1.1.1.1
    volumes:
      - ~/docker-compose/raycast_proxy/cert:/data/cert
